課題①-4送付
Ligaya-yusuke/javascript-questions pull request #3
Opened 2020-12-08 04:23 UTC by Ligaya-yusuke

課題①ー4を送付します。
よろしくお願いします。

2020-12-08 13:06 UTC, myzktkyk requested changes
1点指摘をしております。

2020-12-08 13:06 UTC, myzktkyk commented on js-1-4/js1-4.js
> +  Object.keys(tasks).forEach((value, index) => {
`forEach` を使うほうが簡便かと思います。

```suggestion
  tasks.forEach((value, index) => {
```

2020-12-08 19:56 UTC, Ligaya-yusuke commented on js-1-4/js1-4.js
> +  Object.keys(tasks).forEach((value, index) => {
ありがとうございます。
修正しました。
どちらが良いか判断できず、両方記載してみました。

2020-12-09 12:21 UTC, myzktkyk approved these changes
1点指摘がございますが、先に進んでいただいて構いません！

2020-12-09 12:21 UTC, myzktkyk commented on js-1-4/js1-4.js
> +    console.log(`${index} : [内容]${tasks[index].item}` + `、` + `[ジャンル]${tasks[index].genre}`);
実はこれで大丈夫だったりします ※22行目も同様です。

```suggestion
    console.log(`${index} : [内容]${value.item}` + `、` + `[ジャンル]${value.genre}`);
```

2020-12-10 02:04 UTC, merged